<!-- FAQ.vue -->
<template>
    <div class="faq">
      <h2>Frequently Asked Questions</h2>
      <div v-for="(question, index) in faqList" :key="index" class="faq-item">
        <h3>{{ question.title }}</h3>
        <p>{{ question.answer }}</p>
      </div>
    </div>
  </template>
  
  <script>
  export default {
    data() {
      return {
        faqList: [
        { 
          question: 'How do I shorten a URL?', 
          answer: 'To shorten a URL, simply paste the long URL into the input field and click the "Shorten URL" button. The system will generate a shortened URL for you.' 
        },
        { 
          question: 'Are the shortened URLs permanent?', 
          answer: 'Yes, the shortened URLs generated by our service are permanent. However, please note that we reserve the right to disable or remove shortened URLs that violate our terms of service.' 
        },
        { 
          question: 'Can I customize the shortened URL?', 
          answer: 'At the moment, we do not offer the option to customize shortened URLs. They are generated randomly to ensure uniqueness and prevent collisions.' 
        },
        { 
          question: 'Is there a limit to the number of URLs I can shorten?', 
          answer: 'No, there is no limit to the number of URLs you can shorten using our service. You can shorten as many URLs as you need.' 
        },
        { 
          question: 'How long are the shortened URLs?', 
          answer: 'The length of the shortened URLs may vary, but they are typically around 10-12 characters long. This helps keep the URLs short and easy to share.' 
        },
        { 
          question: 'Can I track the usage of my shortened URLs?', 
          answer: 'Yes, we provide analytics tools that allow you to track the usage of your shortened URLs. You can see metrics such as the number of clicks, geographic location of users, and referral sources.' 
        },
        { 
          question: 'Is the URL shortening service free to use?', 
          answer: 'Yes, our URL shortening service is completely free to use. There are no subscription fees or hidden charges.' 
        },
        { 
          question: 'Do you offer an API for URL shortening?', 
          answer: 'Yes, we offer an API that allows you to programmatically shorten URLs. Please refer to our documentation for more information on how to integrate with our API.' 
        },
        { 
          question: 'Can I preview the destination of a shortened URL before clicking?', 
          answer: 'Yes, you can preview the destination of a shortened URL by hovering over it. This will display the full destination URL in your browser\'s status bar.' 
        },
        { 
          question: 'What happens if I accidentally delete a shortened URL?', 
          answer: 'Once a shortened URL is deleted, it cannot be restored. We recommend exercising caution when deleting URLs and double-checking before confirming.' 
        }
      ]
      };
    }
  };
  </script>
  
  <style scoped>
  .faq {
    margin-top: 20px;
  }
  
  .faq-item {
    margin-bottom: 20px;
  }
  
  .faq-item h3 {
    margin-bottom: 10px;
    color: #333;
  }
  
  .faq-item p {
    color: #666;
  }
  </style>
  